### ISSUE TITLE
Typing throws "Cannot read property 'value' of undefined" errors

### ISSUE THREAD

**Issue by DsNchNtD** [Maloric/CodeMirror-RevisedSearch#2]
Error is this:
codemirror-revisedsearch.js:279 Uncaught TypeError: Cannot read property 'value' of undefined
    at Object.onInput (codemirror-revisedsearch.js:279)
    at HTMLInputElement.CodeMirror.on (advanced-dialog.js:86)

I fixed it locally by changing line 279 from this:
   let query = inputs[0].value;
to this:
   let query = (typeof inputs[0] === 'undefined') ? null : inputs[0].value;

Thanks for this btw. ;)

**Comment by Maloric** [comment]
I can't recreate the problem locally, and while I'm sure that the fix you've suggested would solve the issue, I'm interested to know how it came about.

Can you tell me anything more about your setup?  Specifically, which versions of  RevisedSearch and AdvancedDialog you are using?  What exactly are the steps you go through to open the search or search and replace dialog?

**Comment by DsNchNtD** [comment]
Using the latest version now and the problem seems to have gone away. Thanks for following up.
